version: 0.2.0.{build}

dependencies:
  - HdrHistogram_c
  - cxxopts
  - json
  - fmt
  - Google test

install_dependencies:
  HdrHistogram_c:
    - git clone https://github.com/HdrHistogram/HdrHistogram_c.git
    - cd HdrHistogram_c
    - mkdir build
    - cmake ..
    - cmake --build . --target install
  fmt:
    - git clone https://github.com/xlong88/fmt.git
    - cd fmt
    - mkdir build
    - cmake ..
    - cmake --build . --target install
  googletest:
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - mkdir build
    - cmake ..
    - cmake --build . --target install


build_and_run:
  - git clone https://github.com/xlong88/Serenade.git
  - cd Serenade
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../targets ..
  - cmake --build . --target install 
  - cd ../targets/bin
  
On_Windows_MinGW:
  install_and_build:
    - cmake -DCMAKE_INSTALL_PREFIX=<MinGW_Root> -G"MinGW Makefiles" ..
    - cmake --build . --target install




